import './globals.css'
import localFont from 'next/font/local'

const myFont = localFont({ src: '../public/fonts/JujutsuKaisen.ttf' })


export const metadata = {
  title: 'JujutsuKaisen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}
